### ISSUE TITLE
[Task] 기록 로직 및 레이아웃 구현

### ISSUE THREAD

**Issue by codingbe** [codingbe/baramgen-front#10]
### ISSUE
* Group:  `client`
* Type: `feature`
* Detail: 기록 기능 구현

### TODO
1. [x]  기록 레이아웃 구현
2. [x] 보스 DB 생성
3. [x] CUT 버튼 클릭시 보스의 다음 젠타임 계산
4. [x]   localStorage에 잡은 보스의 데이터 저장
5. [x] 잡은 보스의 다음 젠타임을 보여줌 
6. [x] 컷타임 직접 기록시 로직 구현
### `3h`
