### ISSUE TITLE
[Task] 커뮤니티 레이아웃 구성

### ISSUE THREAD

**Issue by codingbe** [codingbe/baramgen-front#12]
### ISSUE
* Group:  `client`
* Type: `feature`
* Detail: 커뮤니티 레이아웃 구성

### TODO
1. [ ]  게시글 쓸때나 수정할 때 레이아웃
2. [ ] 게시글 읽을때 레이아웃
3. [ ] 커뮤니티 페이지 들어갔을때 레이아웃
 
### `5h`
