### ISSUE TITLE
[Task] 아키텍처 구성

### ISSUE THREAD

**Issue by codingbe** [codingbe/baramgen-front#2]
### ISSUE
* Type: `feature`
* Detail: 아키텍처 구성

### TODO
1. [x]  NextJS 프로젝트 생성
2. [x]  디렉토리 구조 작성
3. [x]  TailwindCSS 설치 및 구성
 
### `1h`
