### ISSUE TITLE
[Task] 커뮤니티 글쓰기

### ISSUE THREAD

**Issue by codingbe** [codingbe/baramgen-front#34]
### ISSUE
* Group:  `client`
* Type: `feature`
* Detail: 커뮤니티 글쓰기 로직

### TODO
1. [ ] 글쓰기 버튼 클릭
2. [ ] 글쓰기 모달 불러오기
3. [ ] 사용자로 부터 내용을 받아 서버로 보냄
4. [ ] 리덕스의 change 상태 변화
