### ISSUE TITLE
[Task] 커뮤니티 글 수정

### ISSUE THREAD

**Issue by codingbe** [codingbe/baramgen-front#36]
### ISSUE
* Group:  `client`,
* Type: `feature`
* Detail: 커뮤니티 글 수정할 때 로직

### TODO
1. [ ] 유저의 아이디와 해당 글의 유저아이디가 같으면 수정 아이콘 보여주기
2. [ ] 수정 아이콘 클릭시 Post 컴포넌트 모달 불러오기
3. [ ] Post 컴포넌트 모달에 불러온 글의 정보 할당
4. [ ] 정보를 서버로 보냄
5. [ ] 리덕스의 change 스테이트 변화
