### ISSUE TITLE
[Task] 댓글 delete

### ISSUE THREAD

**Issue by codingbe** [codingbe/baramgen-front#67]
### ISSUE
* Group:  `client`
* Type: `feature`
* Detail: 댓글 삭제시 로직

### TODO
1. [x] 삭제 아이콘 클릭
2. [x] 서버로 댓글 삭제 요청
3. [x] setChange 함수 실행
